#!/bin/bash

#total amount of memory details displayed.

echo "Memory Space Information"
free -t -m | grep "Total" | awk '{ print "Total Amount of Memory Space : "$2 " MB";
print "Used Amount of Memory Space : "$3" MB";
print "Free Amount of Memory : "$4" MB";

}'

#display network configuration information.

echo "Network information"

ip addr show |grep -w inet |grep -v 127.0.0.1 | awk '{ print "IP Address : " $2 }' | cut -d "/" -f 1

ip addr show | grep -w ether | awk '{ print "MAC Address : " $2 }'
