#!/bin/bash
#Purpose: getopts script
#Version: 1.0
#Created Date: 3/11/18
#Author: Josh Gomez(s3550120)

while getopts "abcde:"  options; do
	case $options in
		a) 

#Display amount of cores being used on system.
awk -F: '/^processor/ { N++} END { print "Number of CPU cores being used on system : "  N }' /proc/cpuinfo;;

*) 
	echo "Incorrect options provided"
	exit 1
	;;
		b)
#the current process priority (nice number).
;;


#total number of process running under the current user.
		c)
	ps -Af | awk '$3 != "root" {print "Processes running under user: " $0}';;

		d)
lsof | grep ' root ' | awk ' {print "Number of open file descriptors: " $NF}' | sort |wc -1;;


esac
done

exit 0;
